# Generated by Django 4.2.1 on 2023-12-07 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingDetails',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('status', models.CharField(choices=[('Booked', 'Booked'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Requested', max_length=100)),
                ('meal_time', models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Supper', 'Supper')], default='Full Day', max_length=100)),
                ('coins_spend', models.IntegerField(default=0)),
                ('booked_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('', 'Select State'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='Kerala', max_length=100)),
                ('status', models.CharField(default='Inactive', max_length=10)),
                ('profile_photo', models.ImageField(null=True, upload_to='restaurant_profile/')),
                ('pancard', models.ImageField(null=True, upload_to='business_pan/')),
                ('description', models.TextField()),
                ('fssai_registration_number', models.DecimalField(decimal_places=0, max_digits=14, unique=True)),
                ('license_number', models.CharField(max_length=100, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('gallery_id', models.AutoField(primary_key=True, serialize=False)),
                ('photo', models.ImageField(null=True, upload_to='restaurant_gallery/')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('', 'Select Category'), ('Menu', 'Menu'), ('Gallery', 'Gallery')], default='Gallery', max_length=100)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_workbench.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2, null=True)),
                ('feedback', models.TextField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_workbench.bookingdetails')),
            ],
        ),
        migrations.CreateModel(
            name='FacilityDetails',
            fields=[
                ('facility_id', models.AutoField(primary_key=True, serialize=False)),
                ('facility_name', models.CharField(choices=[('', 'Select Facility'), ('Table', 'Table'), ('Banquet Hall', 'Banquet Hall'), ('Conference Hall', 'Conference Hall')], default='Table', max_length=100)),
                ('facility_number', models.CharField(max_length=10)),
                ('seat_count', models.IntegerField(default=2)),
                ('seat_arrangement', models.CharField(choices=[('', 'Select Location'), ('Outdoor', 'Outdoor'), ('Indoor', 'Indoor')], default='Indoor', max_length=100, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_workbench.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('', 'Select State'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='Kerala', max_length=100)),
                ('status', models.CharField(default='Active', max_length=10)),
                ('profile_photo', models.ImageField(null=True, upload_to='profile_pictures/')),
                ('id_proof', models.ImageField(null=True, upload_to='customer_identifier/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coins',
            fields=[
                ('coin_id', models.AutoField(primary_key=True, serialize=False)),
                ('coin_quantity', models.IntegerField(default=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_workbench.customer')),
            ],
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_workbench.customer'),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='facility',
            field=models.ManyToManyField(related_name='booking_facilities', to='admin_workbench.facilitydetails'),
        ),
    ]
