# Generated by Django 4.2.1 on 2023-12-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_workbench', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitydetails',
            name='facility_name',
            field=models.CharField(default='Table', max_length=100),
        ),
    ]
