# Generated by Django 4.2.1 on 2023-12-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_workbench', '0002_alter_facilitydetails_facility_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
