# Generated by Django 4.2.1 on 2023-11-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_workbench', '0003_alter_bookingdetails_meal_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitydetails',
            name='facility_number',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
