# Generated by Django 4.2.1 on 2023-12-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_workbench', '0004_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='status',
            field=models.CharField(choices=[('Booked', 'Booked'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Attended', 'Attended')], default='Requested', max_length=100),
        ),
    ]
