# Generated by Django 4.2.1 on 2023-11-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_workbench', '0004_alter_facilitydetails_facility_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitydetails',
            name='facility_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
