# Generated by Django 4.2.1 on 2023-12-14 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_workbench', '0006_restaurant_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='rating',
        ),
    ]
