# Generated by Django 4.2.1 on 2023-11-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_workbench', '0008_alter_facilitydetails_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='status',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Requested', max_length=100),
        ),
        migrations.DeleteModel(
            name='SlotDetails',
        ),
    ]
