# Generated by Django 4.2.1 on 2023-12-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_workbench', '0008_alter_facilitydetails_seat_arrangement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='booked_date',
            field=models.DateField(),
        ),
    ]
