# Generated by Django 4.2.1 on 2023-11-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_workbench', '0009_alter_bookingdetails_status_delete_slotdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='meal_time',
            field=models.CharField(choices=[('', 'Select Meal Time'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Supper', 'Supper'), ('Full Day', 'Full Day')], default='Choose Meal Time', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('', 'Select State'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='Kerala', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitydetails',
            name='facility_name',
            field=models.CharField(choices=[('', 'Select Facility'), ('Table', 'Table'), ('Banquet Hall', 'Banquet Hall'), ('Conference Hall', 'Conference Hall')], default='Table', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitydetails',
            name='floor_number',
            field=models.CharField(choices=[('', 'Select Floor'), ('First Floor', 'First Floor'), ('Second Floor', 'Second Floor'), ('Third Floor', 'Third Floor'), ('Fourth Floor', 'Fourth Floor'), ('Top Floor', 'Top Floor')], default='First Floor', max_length=100),
        ),
        migrations.AlterField(
            model_name='facilitydetails',
            name='position',
            field=models.CharField(choices=[('', 'Select Position'), ('Top', 'Top'), ('Bottom', 'Bottom'), ('Left', 'Left'), ('Right', 'Right'), ('Center', 'Center')], default='Center', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facilitydetails',
            name='seat_arrangement',
            field=models.CharField(choices=[('', 'Select Location'), ('Outdoor', 'Outdoor'), ('Indoor', 'Indoor')], default='Indoor', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('', 'Select Category'), ('Menu', 'Menu'), ('Gallery', 'Gallery')], default='Gallery', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='state',
            field=models.CharField(choices=[('', 'Select State'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal')], default='Kerala', max_length=100),
        ),
    ]
