# Generated by Django 4.2.1 on 2023-11-28 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_workbench', '0010_alter_bookingdetails_meal_time_alter_customer_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='title',
        ),
        migrations.RemoveField(
            model_name='bookingdetails',
            name='facility',
        ),
        migrations.AlterField(
            model_name='bookingdetails',
            name='meal_time',
            field=models.CharField(choices=[('', 'Select Meal Time'), ('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Supper', 'Supper')], default='Full Day', max_length=100),
        ),
        migrations.AddField(
            model_name='bookingdetails',
            name='facility',
            field=models.ManyToManyField(to='admin_workbench.facilitydetails'),
        ),
    ]
