# Generated by Django 4.2.1 on 2023-11-30 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_workbench', '0011_remove_bookingdetails_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingdetails',
            name='slot_requested',
        ),
        migrations.RemoveField(
            model_name='facilitydetails',
            name='floor_number',
        ),
        migrations.RemoveField(
            model_name='facilitydetails',
            name='position',
        ),
    ]
