# Generated by Django 4.2.1 on 2023-12-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_workbench', '0014_alter_bookingdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='meal_time',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Supper', 'Supper')], default='Full Day', max_length=100),
        ),
    ]
