# Generated by Django 4.2.1 on 2023-12-04 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_workbench', '0015_alter_bookingdetails_meal_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingdetails',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
